# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_records.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sales_records.proto\"\r\n\x0b\x45mptyMesage\"\'\n\x18PingSalesRecordsResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"\x83\x01\n\x13SalesRecordsRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x12\n\nunits_sold\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\t\x12\x11\n\tunit_cost\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\"$\n\x14SalesRecordsResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x8c\x01\n\x0cSalesRecords\x12;\n\x10PingSalesRecords\x12\x0c.EmptyMesage\x1a\x19.PingSalesRecordsResponse\x12?\n\x10SendSalesRecords\x12\x14.SalesRecordsRequest\x1a\x15.SalesRecordsResponseb\x06proto3')



_EMPTYMESAGE = DESCRIPTOR.message_types_by_name['EmptyMesage']
_PINGSALESRECORDSRESPONSE = DESCRIPTOR.message_types_by_name['PingSalesRecordsResponse']
_SALESRECORDSREQUEST = DESCRIPTOR.message_types_by_name['SalesRecordsRequest']
_SALESRECORDSRESPONSE = DESCRIPTOR.message_types_by_name['SalesRecordsResponse']
EmptyMesage = _reflection.GeneratedProtocolMessageType('EmptyMesage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESAGE,
  '__module__' : 'sales_records_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMesage)
  })
_sym_db.RegisterMessage(EmptyMesage)

PingSalesRecordsResponse = _reflection.GeneratedProtocolMessageType('PingSalesRecordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGSALESRECORDSRESPONSE,
  '__module__' : 'sales_records_pb2'
  # @@protoc_insertion_point(class_scope:PingSalesRecordsResponse)
  })
_sym_db.RegisterMessage(PingSalesRecordsResponse)

SalesRecordsRequest = _reflection.GeneratedProtocolMessageType('SalesRecordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDSREQUEST,
  '__module__' : 'sales_records_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordsRequest)
  })
_sym_db.RegisterMessage(SalesRecordsRequest)

SalesRecordsResponse = _reflection.GeneratedProtocolMessageType('SalesRecordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDSRESPONSE,
  '__module__' : 'sales_records_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordsResponse)
  })
_sym_db.RegisterMessage(SalesRecordsResponse)

_SALESRECORDS = DESCRIPTOR.services_by_name['SalesRecords']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESAGE._serialized_start=23
  _EMPTYMESAGE._serialized_end=36
  _PINGSALESRECORDSRESPONSE._serialized_start=38
  _PINGSALESRECORDSRESPONSE._serialized_end=77
  _SALESRECORDSREQUEST._serialized_start=80
  _SALESRECORDSREQUEST._serialized_end=211
  _SALESRECORDSRESPONSE._serialized_start=213
  _SALESRECORDSRESPONSE._serialized_end=249
  _SALESRECORDS._serialized_start=252
  _SALESRECORDS._serialized_end=392
# @@protoc_insertion_point(module_scope)
